# Generated by Django 5.1.4 on 2025-05-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.BinaryField(primary_key=True, serialize=False)),
                ("max_task_count", models.IntegerField()),
                ("finished_task_count", models.IntegerField()),
                ("mac_address", models.BinaryField()),
                ("tasks_list", models.TextField()),
            ],
        ),
    ]
